### ISSUE TITLE
Questions about Ubuntu support

### ISSUE THREAD

**Issue by rajinders** [liupeirong/Azure#1]
Thanks for providing this script along with VM customization. This will save me many hours.

There is a comment in the documentation says that there is a regression bug with provisioning the 2nd NIC. I am trying to understand how to work around it. I need to provision a MySQL cluster in US Central soon. I was thinking about using Ubuntu but I am fine with CentOS as well. Based on the fact your supported CentOS first is that the OS you recommend at this time.

finally you have an example that says that you can provision 2nd NIC and disk striping.
In this example you only use 1 disk. How is striping implemented with just 1 data disk. Are you striping OS disk and 1 data disk?

To deploy a 3 node cluster with disk striping and 2nd NIC: 
64  
65     .\DeployPXC.ps1 -SubscriptionName "mysubscription" -StorageAccountName "mystorage" -ServiceName "myservice" `
66                     -VNetName "myvnet" -DBSubnet "dbsubnet" -DBNodeIPs "10.0.0.1,10.0.0.2,10.0.0.3"` 
67                     -LoadBalancerIP "10.0.0.4" -VMSize "Large" -NumOfDisks 1 -DiskSizeInGB 10 -VMNamePrefix "azpxc" `
68                     -VMUser "azureuser" -VMPassword "s3cret#"` 
69                     -SecondNICName "eth1" -SecondNICSubnet "clustersubnet" -SecondNICIPs "10.1.0.4,10.1.0.5,10.1.0.6" 

Thanks

**Comment by liupeirong** [comment]
Sorry I didn't see this until now.  The 2nd NIC problem with Ubuntu should have been fixed. Yes, I've done most of the testing on CentOS.  
If you specify only 1 disk, then no striping will be done. 
BTW, this script deploys Azure resources in "classic" or "Azure Service Management" stack.  Moving forward, it's better to deploy resources using "Azure Resource Management" (ARM) stack.  We now support template based deployment on ARM.  To deploy a Percona cluster, you can use this template: https://github.com/Azure/azure-quickstart-templates/tree/master/mysql-ha-pxc.  You can find MySQL master/slave replication, and MariaDB Galera cluster in the same repo.
